import { 
  ClipboardList, 
  Building2, 
  Globe, 
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  ExternalLink,
  X,
  MapPin,
  HardHat,
  Factory,
  Search,
  LayoutDashboard,
  Signal,
  Folder,
  Settings,
  LogOut,
  Bell,
  ChevronRight,
  MoreVertical,
  Plus,
  Filter,
  Download,
  TrendingUp,
  Users,
  Clock,
  CheckCircle2,
  AlertCircle,
  FileText,
  Mail,
  Phone,
  Github,
  Twitter,
  Linkedin,
  Monitor,
  Database,
  Shield,
  Zap,
  Menu,
  ChevronDown,
  User
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Signals: Signal,
  Projects: Folder,
  Settings: Settings,
  Logout: LogOut,
  Search: Search,
  Notifications: Bell,
  ChevronRight: ChevronRight,
  MoreVertical: MoreVertical,
  Plus: Plus,
  Filter: Filter,
  Download: Download,
  Globe: Globe,
  TrendingUp: TrendingUp,
  Users: Users,
  Clock: Clock,
  Check: CheckCircle2,
  Alert: AlertCircle,
  File: FileText,
  Mail: Mail,
  Phone: Phone,
  ExternalLink: ExternalLink,
  Github: Github,
  Twitter: Twitter,
  Linkedin: Linkedin,
  Monitor: Monitor,
  Database: Database,
  Shield: Shield,
  Zap: Zap,
  Menu: Menu,
  X: X,
  ChevronDown: ChevronDown,
  User: User,
  ClipboardList: ClipboardList,
  Building2: Building2,
  ArrowLeft: ArrowLeft,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  ArrowUpDown: ArrowUpDown,
  MapPin: MapPin,
  HardHat: HardHat,
  Factory: Factory
};
