import { 
  LayoutDashboard, 
  Signal, 
  FolderCanvas, 
  Settings, 
  LogOut, 
  Search, 
  Bell, 
  ChevronRight, 
  MoreVertical,
  Plus,
  Filter,
  Download,
  Globe,
  TrendingUp,
  Users,
  Clock,
  CheckCircle2,
  AlertCircle,
  FileText,
  Mail,
  Phone,
  ExternalLink,
  Github,
  Twitter,
  Linkedin,
  Monitor,
  Database,
  Shield,
  Zap,
  Menu,
  X,
  ChevronDown,
  User
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Signals: Signal,
  Projects: FolderCanvas,
  Settings: Settings,
  Logout: LogOut,
  Search: Search,
  Notifications: Bell,
  ChevronRight: ChevronRight,
  MoreVertical: MoreVertical,
  Plus: Plus,
  Filter: Filter,
  Download: Download,
  Globe: Globe,
  TrendingUp: TrendingUp,
  Users: Users,
  Clock: Clock,
  Check: CheckCircle2,
  Alert: AlertCircle,
  File: FileText,
  Mail: Mail,
  Phone: Phone,
  ExternalLink: ExternalLink,
  Github: Github,
  Twitter: Twitter,
  Linkedin: Linkedin,
  Monitor: Monitor,
  Database: Database,
  Shield: Shield,
  Zap: Zap,
  Menu: Menu,
  X: X,
  ChevronDown: ChevronDown,
  User: User
};
